from __future__ import annotations
import asyncio
import uuid
from pathlib import Path

from ..config import settings
from ..models.pipeline import (
    Job, JobStatus, Section, MediaAsset, AudioAsset,
    Clip, Track, Timeline, SubtitleCue,
)
from ..services import job_store
from ..services.scraper import fetch_html, extract_sections, detect_paywall, extract_brand_colors
from ..services import claude_service, pexels_service
from ..services import stability_service as imagen_service
from ..services import elevenlabs_service


async def run_pipeline(job_id: str, url: str, voice_id: str = "Rachel") -> None:
    job = job_store.get_job(job_id)
    if not job:
        return

    async def update(status: JobStatus, progress: int, **kw):
        job.status = status
        job.progress = progress
        for k, v in kw.items():
            setattr(job, k, v)
        job_store.set_job(job)
        await job_store.publish(job_id, {
            "status": status.value,
            "progress": progress,
        })

    try:
        # ── 1. SCRAPING ──────────────────────────────────────────────────────
        await update(JobStatus.SCRAPING, 5)
        html = await fetch_html(url)
        if detect_paywall(html):
            raise ValueError(
                "This article is behind a paywall. Only free/public articles can be processed. "
                "Try a free article from this newsletter, or a different newsletter URL."
            )
        sections = extract_sections(html)
        if not sections:
            raise ValueError(
                "Could not extract any text from this page. "
                "The URL may point to a homepage rather than a specific article, "
                "or the content may use a format the scraper doesn't support."
            )
        sections = sections[:8]
        job.sections = sections
        job_store.set_job(job)

        # ── 2. ANALYZING ─────────────────────────────────────────────────────
        # Single Claude call: produces one concise educational voice_script per
        # scraped section. Total ≤ 75 words (≤ 30 seconds at 2.5 words/sec).
        await update(JobStatus.ANALYZING, 20)
        try:
            result = await claude_service.analyze_newsletter(sections)
            section_data = result["sections"]
        except Exception:
            # Fallback: truncate raw_text directly
            section_data = [
                {
                    "voice_script":      s.raw_text[:80],
                    "scene_description": s.heading,
                    "keywords":          [s.heading or "news"],
                }
                for s in sections
            ]

        # Annotate each scraped section with Claude's per-section summary
        for i, sec in enumerate(sections):
            if i < len(section_data):
                data = section_data[i]
                sec.voice_script = data.get("voice_script", sec.raw_text[:80])
                sec.summary = data.get("scene_description", sec.heading)
                sec.keywords = data.get("keywords", [sec.heading or "news"])
            else:
                sec.voice_script = sec.raw_text[:80]
                sec.keywords = [sec.heading or "news"]

        # Generate writing + brand profiles concurrently to avoid serial latency
        colors = extract_brand_colors(html)
        results = await asyncio.gather(
            claude_service.generate_writing_profile(sections),
            claude_service.generate_brand_profile(sections, colors),
            return_exceptions=True,
        )
        job_dir = settings.jobs_path / job_id
        if isinstance(results[0], str):
            (job_dir / "skills.md").write_text(results[0], encoding="utf-8")
        else:
            print(f"[skills] generate_writing_profile failed: {results[0]}")
        if isinstance(results[1], str):
            (job_dir / "brand.md").write_text(results[1], encoding="utf-8")
        else:
            print(f"[brand] generate_brand_profile failed: {results[1]}")

        await update(JobStatus.ANALYZING, 38)
        job.sections = sections
        job_store.set_job(job)

        # ── 3. GENERATING MEDIA ───────────────────────────────────────────────
        # Each segment gets a dramatic cinematic portrait image generated by
        # Google Imagen (scene_description as prompt). Falls back to Pexels
        # stock footage/photo if Imagen is unavailable.
        await update(JobStatus.FETCHING_MEDIA, 40)
        job_dir = settings.jobs_path / job_id
        media_dir = job_dir / "media"
        media_dir.mkdir(parents=True, exist_ok=True)

        media_assets: list[MediaAsset] = []
        n = max(1, len(job.sections))
        for i, sec in enumerate(job.sections):
            asset = await _generate_scene_media(sec, media_dir)
            if asset:
                media_assets.append(asset)
            await update(JobStatus.FETCHING_MEDIA, 40 + int((i + 1) / n * 23))  # 40→63%

        job.media_assets = media_assets
        job_store.set_job(job)

        # ── 4. GENERATING AUDIO ───────────────────────────────────────────────
        await update(JobStatus.GENERATING_AUDIO, 65)
        audio_dir = job_dir / "audio"
        audio_dir.mkdir(parents=True, exist_ok=True)

        audio_assets: list[AudioAsset] = []
        section_word_timestamps: dict[str, list] = {}
        for i, sec in enumerate(job.sections):
            audio_path = audio_dir / f"{sec.id}.mp3"
            ok, words, duration = await elevenlabs_service.generate_audio(
                sec.voice_script, voice_id, audio_path, settings.elevenlabs_api_key
            )
            if ok:
                audio_assets.append(AudioAsset(
                    id=str(uuid.uuid4()),
                    section_id=sec.id,
                    local_path=str(audio_path),
                    duration_s=duration,
                ))
                section_word_timestamps[sec.id] = words
            else:
                # Fallback: estimate duration from word count instead of polling ElevenLabs
                estimated = claude_service.estimate_duration_s(sec.voice_script)
                audio_assets.append(AudioAsset(
                    id=str(uuid.uuid4()),
                    section_id=sec.id,
                    local_path="",
                    duration_s=estimated,
                ))
                section_word_timestamps[sec.id] = []
            await update(JobStatus.GENERATING_AUDIO, 65 + int((i + 1) / n * 18))  # 65→83%

        job.audio_assets = audio_assets
        job_store.set_job(job)

        # ── 5. BUILD TIMELINE ─────────────────────────────────────────────────
        await update(JobStatus.BUILD_TIMELINE, 85)
        timeline = _build_initial_timeline(job, section_word_timestamps)
        job.timeline = timeline
        job_store.set_job(job)

        # ── 6. READY ──────────────────────────────────────────────────────────
        # Single publish so the SSE client receives timeline before closing the stream.
        # (A prior update() call would send a "ready" event that closes the stream,
        #  causing the second timeline publish to be dropped.)
        job.status = JobStatus.READY
        job.progress = 100
        job_store.set_job(job)
        await job_store.publish(job_id, {
            "status": JobStatus.READY.value,
            "progress": 100,
            "timeline": timeline.model_dump(),
        })

    except Exception as e:
        job.status = JobStatus.ERROR
        job.error = str(e)
        job_store.set_job(job)
        await job_store.publish(job_id, {
            "status": JobStatus.ERROR.value,
            "progress": job.progress,
            "error": str(e),
        })


async def _generate_scene_media(sec: Section, media_dir: Path) -> MediaAsset | None:
    """
    Generate a dramatic cinematic portrait image for a commercial scene.
    Primary:  Google Imagen using the segment's scene_description (stored in sec.summary).
    Fallback: Pexels stock video → Pexels photo using sec.keywords.
    """
    google_key = settings.google_api_key

    # Primary: AI-generated cinematic image
    if google_key and sec.summary:
        prompt = (
            f"Dramatic cinematic commercial scene, portrait 9:16 format: {sec.summary}. "
            "Professional photography, dramatic lighting, high contrast, ultra-realistic, "
            "magazine quality, no text, no watermarks, no people unless essential."
        )
        dest = media_dir / f"{sec.id}_commercial.jpg"
        ok = await imagen_service.generate_image(prompt, google_key, dest)
        if ok:
            return MediaAsset(
                id=str(uuid.uuid4()),
                section_id=sec.id,
                media_type="image",
                source="google",
                local_path=str(dest),
                url="",
            )

    # Fallback: Pexels stock footage / photo
    pexels_key = settings.pexels_api_key
    if pexels_key and sec.keywords:
        for keyword in sec.keywords[:2]:
            videos = await pexels_service.search_videos(keyword, pexels_key, per_page=3)
            if videos:
                v = videos[0]
                dest = media_dir / f"{sec.id}_video.mp4"
                ok = await pexels_service.download_asset(v["url"], dest)
                if ok:
                    return MediaAsset(
                        id=str(uuid.uuid4()),
                        section_id=sec.id,
                        media_type="video",
                        source="pexels",
                        local_path=str(dest),
                        url=v["url"],
                        duration_s=float(v.get("duration") or 10),
                    )

        for keyword in sec.keywords[:2]:
            photos = await pexels_service.search_photos(keyword, pexels_key, per_page=3)
            if photos:
                p = photos[0]
                dest = media_dir / f"{sec.id}_photo.jpg"
                ok = await pexels_service.download_asset(p["url"], dest)
                if ok:
                    return MediaAsset(
                        id=str(uuid.uuid4()),
                        section_id=sec.id,
                        media_type="image",
                        source="pexels",
                        local_path=str(dest),
                        url=p["url"],
                    )

    return None


def _build_initial_timeline(job: Job, section_word_timestamps: dict[str, list] | None = None) -> Timeline:
    visual_clips: list[Clip] = []
    audio_clips: list[Clip] = []
    subtitle_clips: list[Clip] = []

    media_by_section = {a.section_id: a for a in job.media_assets}
    audio_by_section = {a.section_id: a for a in job.audio_assets}

    cursor = 0.0

    for sec in job.sections:
        audio = audio_by_section.get(sec.id)
        media = media_by_section.get(sec.id)
        duration = audio.duration_s if audio else claude_service.estimate_duration_s(sec.voice_script)

        if media:
            visual_clips.append(Clip(
                id=str(uuid.uuid4()),
                clip_type="visual",
                section_id=sec.id,
                start_s=cursor,
                duration_s=duration,
                media_type=media.media_type,
                local_path=media.local_path,
            ))

        if audio and audio.local_path:
            audio_clips.append(Clip(
                id=str(uuid.uuid4()),
                clip_type="audio",
                section_id=sec.id,
                start_s=cursor,
                duration_s=duration,
                audio_path=audio.local_path,
            ))

        words = (section_word_timestamps or {}).get(sec.id, [])
        if words:
            cues = _build_subtitle_cues_from_words(words, cursor)
        else:
            cues = _build_subtitle_cues(sec.voice_script, cursor, duration)

        subtitle_clips.append(Clip(
            id=str(uuid.uuid4()),
            clip_type="subtitle",
            section_id=sec.id,
            start_s=cursor,
            duration_s=duration,
            subtitle_text=sec.voice_script,
            cues=cues,
        ))

        cursor += duration

    tracks = [
        Track(id="visual",   track_type="visual",   clips=visual_clips),
        Track(id="audio",    track_type="audio",    clips=audio_clips),
        Track(id="subtitle", track_type="subtitle", clips=subtitle_clips),
    ]

    return Timeline(
        job_id=job.id,
        tracks=tracks,
        total_duration_s=cursor,
    )


def _build_subtitle_cues_from_words(
    words: list[tuple[str, float, float]], section_start: float, words_per_cue: int = 7
) -> list[SubtitleCue]:
    cues: list[SubtitleCue] = []
    for i in range(0, len(words), words_per_cue):
        chunk = words[i : i + words_per_cue]
        if not chunk:
            continue
        cues.append(SubtitleCue(
            start_s=section_start + chunk[0][1],
            end_s=section_start + chunk[-1][2],
            text=" ".join(w[0] for w in chunk),
        ))
    return cues


def _build_subtitle_cues(text: str, start_s: float, total_dur: float) -> list[SubtitleCue]:
    words = text.split()
    if not words:
        return []
    words_per_cue = 7
    chunks = [words[i : i + words_per_cue] for i in range(0, len(words), words_per_cue)]
    chunk_dur = total_dur / len(chunks)
    return [
        SubtitleCue(
            start_s=start_s + i * chunk_dur,
            end_s=start_s + (i + 1) * chunk_dur,
            text=" ".join(chunk),
        )
        for i, chunk in enumerate(chunks)
    ]
